= Apellicon

Apellicon is named after a famous greek book collector from 1st Century BC.

Apellicon is an API registry and search engine. It provides a basic search UI for API discovery and an api for uploading API specifications.

* OpenAPI 2/3 JSON and YAML formats
* WADL XML interface definitions

== In a hurry

If you have docker installed just run:

    docker build --tag apellicon -f docker/Dockerfile .

    docker-compose docker/docker-componse up

This will build apillicon:latest, download an elastic search container and if everything works as planned you can open the app in your browser:

    http://localhost:8000

== Adding data

    sh scripts/upload.sh

....

include::scripts/upload.sh[]

....

Uploads some example API specs.

== Development

Running all tests:

    bazel test //...

Building and Running

    bazel run //service/apellicon

You will need a running elastic search instance

    ./scripts/es-start.sh

    docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.6.2

If you have a local elastic search instance running set

    ENV ELASTICSEARCH_URL=http://<host>:<port>

